// DSE Core Vocabulary Seed Data
// ~100 core words sorted by difficulty level (1-5)

export const dseCoreVocabulary = [
  // Level 1 (Beginner)
  { word: "achieve", definition: "完成；实现", difficultyLevel: 1, exampleSentence: "He worked hard to achieve his goal." },
  { word: "appear", definition: "出现；似乎", difficultyLevel: 1, exampleSentence: "The sun appeared from behind the clouds." },
  { word: "benefit", definition: "益处；使受益", difficultyLevel: 1, exampleSentence: "Exercise benefits your health." },
  { word: "cause", definition: "原因；导致", difficultyLevel: 1, exampleSentence: "Smoking can cause serious health problems." },
  { word: "chance", definition: "机会；可能性", difficultyLevel: 1, exampleSentence: "This is your big chance to succeed." },
  { word: "change", definition: "改变；变化", difficultyLevel: 1, exampleSentence: "Climate change affects everyone." },
  { word: "choose", definition: "选择；决定", difficultyLevel: 1, exampleSentence: "You can choose any topic you like." },
  { word: "connect", definition: "连接；联结", difficultyLevel: 1, exampleSentence: "The bridge connects the two islands." },
  { word: "consider", definition: "考虑；认为", difficultyLevel: 1, exampleSentence: "Please consider my suggestion." },
  { word: "continue", definition: "继续；持续", difficultyLevel: 1, exampleSentence: "The game will continue after the rain." },
  { word: "control", definition: "控制；管理", difficultyLevel: 1, exampleSentence: "You need to control your temper." },
  { word: "develop", definition: "发展；开发", difficultyLevel: 1, exampleSentence: "We need to develop new technologies." },
  { word: "different", definition: "不同的；差异的", difficultyLevel: 1, exampleSentence: "We have different opinions on this issue." },
  { word: "difficult", definition: "困难的；难的", difficultyLevel: 1, exampleSentence: "The final exam was very difficult." },
  { word: "effect", definition: "影响；效果", difficultyLevel: 1, exampleSentence: "The new law had a positive effect." },
  { word: "environment", definition: "环境；周围", difficultyLevel: 1, exampleSentence: "We must protect our environment." },
  { word: "experience", definition: "经验；经历", difficultyLevel: 1, exampleSentence: "She has years of teaching experience." },
  { word: "factor", definition: "因素；要素", difficultyLevel: 1, exampleSentence: "Time management is an important factor." },
  { word: "focus", definition: "聚焦；焦点", difficultyLevel: 1, exampleSentence: "Please focus on your work." },
  { word: "future", definition: "未来；将来", difficultyLevel: 1, exampleSentence: "We need to plan for the future." },
  { word: "growth", definition: "增长；成长", difficultyLevel: 1, exampleSentence: "Economic growth is important." },
  { word: "happen", definition: "发生；出现", difficultyLevel: 1, exampleSentence: "I wonder what will happen next." },
  { word: "important", definition: "重要的；重大的", difficultyLevel: 1, exampleSentence: "This is an important meeting." },
  { word: "improve", definition: "改善；提高", difficultyLevel: 1, exampleSentence: "You should improve your English." },
  { word: "increase", definition: "增加；增长", difficultyLevel: 1, exampleSentence: "The population has increased dramatically." },
  { word: "influence", definition: "影响；势力", difficultyLevel: 1, exampleSentence: "His writings influenced many people." },
  { word: "information", definition: "信息；资料", difficultyLevel: 1, exampleSentence: "We need more information." },
  { word: "interest", definition: "兴趣；利益", difficultyLevel: 1, exampleSentence: "She has an interest in painting." },
  { word: "involve", definition: "包含；涉及", difficultyLevel: 1, exampleSentence: "The project involves a lot of work." },
  { word: "issue", definition: "问题；议题", difficultyLevel: 1, exampleSentence: "Climate change is a major issue." },

  // Level 2 (Elementary)
  { word: "adequate", definition: "足够的；适当的", difficultyLevel: 2, exampleSentence: "The supply is not adequate to the demand." },
  { word: "analyze", definition: "分析；研究", difficultyLevel: 2, exampleSentence: "We need to analyze the data carefully." },
  { word: "approach", definition: "方法；途径", difficultyLevel: 2, exampleSentence: "We need a new approach to this problem." },
  { word: "assess", definition: "评估；评价", difficultyLevel: 2, exampleSentence: "We need to assess the situation first." },
  { word: "available", definition: "可获得的；可利用的", difficultyLevel: 2, exampleSentence: "This information is available online." },
  { word: "avoid", definition: "避免；避开", difficultyLevel: 2, exampleSentence: "You should avoid making the same mistake." },
  { word: "balance", definition: "平衡；均衡", difficultyLevel: 2, exampleSentence: "We need to balance work and life." },
  { word: "challenge", definition: "挑战；质疑", difficultyLevel: 2, exampleSentence: "Face your challenges head-on." },
  { word: "concept", definition: "概念；观念", difficultyLevel: 2, exampleSentence: "This concept is difficult to understand." },
  { word: "consequence", definition: "后果；结果", difficultyLevel: 2, exampleSentence: "You must accept the consequences." },
  { word: "contribute", definition: "贡献；捐赠", difficultyLevel: 2, exampleSentence: "Everyone should contribute to society." },
  { word: "convenient", definition: "方便的；便利的", difficultyLevel: 2, exampleSentence: "Online shopping is very convenient." },
  { word: "definite", definition: "明确的；肯定的", difficultyLevel: 2, exampleSentence: "We need a definite answer by tomorrow." },
  { word: "demonstrate", definition: "证明；展示", difficultyLevel: 2, exampleSentence: "He demonstrated his new technique." },
  { word: "determine", definition: "确定；决定", difficultyLevel: 2, exampleSentence: "We need to determine the cause." },
  { word: "efficient", definition: "高效的；有能力的", difficultyLevel: 2, exampleSentence: "She is very efficient at her work." },
  { word: "emphasize", definition: "强调；着重", difficultyLevel: 2, exampleSentence: "He emphasized the importance of hard work." },
  { word: "establish", definition: "建立；创建", difficultyLevel: 2, exampleSentence: "The company was established in 1990." },
  { word: "evaluate", definition: "评价；评估", difficultyLevel: 2, exampleSentence: "We need to evaluate our progress." },
  { word: "furthermore", definition: "此外；而且", difficultyLevel: 2, exampleSentence: "Furthermore, there is another issue to consider." },
  { word: "generous", definition: "慷慨的；大方的", difficultyLevel: 2, exampleSentence: "He is generous with his money." },
  { word: "genuine", definition: "真诚的；真实的", difficultyLevel: 2, exampleSentence: "He showed genuine concern." },
  { word: "identify", definition: "识别；认出", difficultyLevel: 2, exampleSentence: "Can you identify the problem?" },
  { word: "illustrate", definition: "说明；图解", difficultyLevel: 2, exampleSentence: "Let me illustrate this point with an example." },
  { word: "imply", definition: "暗示；意味", difficultyLevel: 2, exampleSentence: "What does this imply?" },
  { word: "indicate", definition: "表明；指示", difficultyLevel: 2, exampleSentence: "The results indicate a positive trend." },
  { word: "initial", definition: "最初的；开始的", difficultyLevel: 2, exampleSentence: "My initial impression was good." },
  { word: "instructions", definition: "指令；说明", difficultyLevel: 2, exampleSentence: "Please read the instructions carefully." },
  { word: "integrate", definition: "整合；融合", difficultyLevel: 2, exampleSentence: "We need to integrate these systems." },
  { word: "interpret", definition: "解释；理解", difficultyLevel: 2, exampleSentence: "How do you interpret this sentence?" },

  // Level 3 (Intermediate)
  { word: "acquire", definition: "获得；习得", difficultyLevel: 3, exampleSentence: "He acquired a lot of knowledge through reading." },
  { word: "alternative", definition: "可供选择的；替代", difficultyLevel: 3, exampleSentence: "We need to find an alternative solution." },
  { word: "ambiguous", definition: "模棱两可的；含糊不清", difficultyLevel: 3, exampleSentence: "The statement was ambiguous." },
  { word: "anticipate", definition: "预期；预料", difficultyLevel: 3, exampleSentence: "We anticipated the problem." },
  { word: "approximate", definition: "大约的；近似", difficultyLevel: 3, exampleSentence: "The approximate cost is $1000." },
  { word: "comprehensive", definition: "全面的；综合的", difficultyLevel: 3, exampleSentence: "We have a comprehensive plan." },
  { word: "consecutive", definition: "连续的；连贯的", difficultyLevel: 3, exampleSentence: "It rained for five consecutive days." },
  { word: "consistent", definition: "一致的；持续的", difficultyLevel: 3, exampleSentence: "His performance has been consistent." },
  { word: "contradict", definition: "矛盾；反驳", difficultyLevel: 3, exampleSentence: "The two statements contradict each other." },
  { word: "conversely", definition: "相反地；反之", difficultyLevel: 3, exampleSentence: "Conversely, the opposite effect can also occur." },
  { word: "convincing", definition: "有说服力的；令人信服", difficultyLevel: 3, exampleSentence: "His argument was very convincing." },
  { word: "correspond", definition: "符合；一致", difficultyLevel: 3, exampleSentence: "Your answer corresponds with mine." },
  { word: "cumulative", definition: "累积的；累计", difficultyLevel: 3, exampleSentence: "The effects are cumulative." },
  { word: "nevertheless", definition: "然而；不过", difficultyLevel: 3, exampleSentence: "It was a hard day. Nevertheless, we finished on time." },
  { word: "diminish", definition: "减少；降低", difficultyLevel: 3, exampleSentence: "Their influence has diminished over time." },
  { word: "nevertheless", definition: "然而；不过", difficultyLevel: 3, exampleSentence: "It was raining. Nevertheless, we went out." },
  { word: "distinguish", definition: "区分；辨别", difficultyLevel: 3, exampleSentence: "It's hard to distinguish between the two." },
  { word: "eliminate", definition: "消除；排除", difficultyLevel: 3, exampleSentence: "We need to eliminate poverty." },
  { word: "empirical", definition: "实证的；经验主义", difficultyLevel: 3, exampleSentence: "Empirical evidence supports this theory." },
  { word: "facilitate", definition: "促进；使便利", difficultyLevel: 3, exampleSentence: "New technology facilitates communication." },
  { word: "foundation", definition: "基础；基金会", difficultyLevel: 3, exampleSentence: "This laid the foundation for future growth." },
  { word: "fundamental", definition: "基本的；根本", difficultyLevel: 3, exampleSentence: "This is a fundamental change in policy." },
  { word: "hence", definition: "因此；所以", difficultyLevel: 3, exampleSentence: "Hence, we can conclude that..." },
  { word: "hypothesis", definition: "假设；假说", difficultyLevel: 3, exampleSentence: "The hypothesis has not been proven." },
  { word: "ignore", definition: "忽视；忽略", difficultyLevel: 3, exampleSentence: "You can't ignore the problem any longer." },

  // Level 4 (Upper-intermediate)
  { word: "accommodate", definition: "容纳；适应", difficultyLevel: 4, exampleSentence: "The hotel can accommodate 500 guests." },
  { word: "analogous", definition: "类似的；相似", difficultyLevel: 4, exampleSentence: "This situation is analogous to our own." },
  { word: "articulate", definition: "清晰表达；有力的", difficultyLevel: 4, exampleSentence: "She is very articulate." },
  { word: "complementary", definition: "互补的；补充", difficultyLevel: 4, exampleSentence: "The two approaches are complementary." },
  { word: "conspicuous", definition: "显眼的；明显的", difficultyLevel: 4, exampleSentence: "There was a conspicuous mistake in the report." },
  { word: "concurrently", definition: "同时；并行", difficultyLevel: 4, exampleSentence: "He holds two jobs concurrently." },
  { word: "domain", definition: "领域；范围", difficultyLevel: 4, exampleSentence: "This is outside my domain of expertise." },
  { word: "empirical", definition: "基于实验的；经验的", difficultyLevel: 4, exampleSentence: "The theory needs empirical verification." },
  { word: "explicit", definition: "明确的；清晰的", difficultyLevel: 4, exampleSentence: "He gave explicit instructions." },
  { word: "flourish", definition: "繁荣；兴旺", difficultyLevel: 4, exampleSentence: "The arts flourished during that period." },
  { word: "gauge", definition: "测量；估计", difficultyLevel: 4, exampleSentence: "It's difficult to gauge public opinion." },
  { word: "homogeneous", definition: "同质的；均匀", difficultyLevel: 4, exampleSentence: "The population is relatively homogeneous." },
  { word: "hypothetical", definition: "假设的；假定", difficultyLevel: 4, exampleSentence: "Let's consider a hypothetical situation." },
  { word: "implicit", definition: "隐含的；暗示", difficultyLevel: 4, exampleSentence: "There was an implicit understanding between them." },
  { word: "inherent", definition: "固有的；内在", difficultyLevel: 4, exampleSentence: "This problem is inherent in the system." },
  { word: "innovate", definition: "创新；改革", difficultyLevel: 4, exampleSentence: "We need to innovate to stay competitive." },
  { word: "interdependent", definition: "相互依存的", difficultyLevel: 4, exampleSentence: "We live in an interdependent world." },
  { word: "methodology", definition: "方法论；方法学", difficultyLevel: 4, exampleSentence: "The study uses qualitative methodology." },
  { word: "nevertheless", definition: "然而；虽然如此", difficultyLevel: 4, exampleSentence: "It was expensive. Nevertheless, we bought it." },
  { word: "notwithstanding", definition: "尽管；虽然", difficultyLevel: 4, exampleSentence: "Notwithstanding the bad weather, we went ahead." },

  // Level 5 (Advanced)
  { word: "abstract", definition: "抽象的；摘要", difficultyLevel: 5, exampleSentence: "He is good at abstract thinking." },
  { word: "albeit", definition: "虽然；尽管", difficultyLevel: 5, exampleSentence: "He continued, albeit reluctantly." },
  { word: "ascertain", definition: "确定；查明", difficultyLevel: 5, exampleSentence: "We need to ascertain the facts." },
  { word: "cognitive", definition: "认知的；认识", difficultyLevel: 5, exampleSentence: "Cognitive development is important in childhood." },
  { word: "concomitant", definition: "伴随的；相伴", difficultyLevel: 5, exampleSentence: "Social change brings concomitant problems." },
  { word: "counterintuitive", definition: "反直觉的", difficultyLevel: 5, exampleSentence: "The result is counterintuitive but correct." },
  { word: "delineate", definition: "描绘；描述", difficultyLevel: 5, exampleSentence: "The report delineates the main problems." },
  { word: "epistemological", definition: "认识论的", difficultyLevel: 5, exampleSentence: "This is an epistemological question." },
  { word: "heterogeneous", definition: "异质的；多样", difficultyLevel: 5, exampleSentence: "The group is heterogeneous in background." },
  { word: "methodological", definition: "方法论的；方法", difficultyLevel: 5, exampleSentence: "There are methodological flaws in the study." },
  { word: "paradigm", definition: "范例；范式", difficultyLevel: 5, exampleSentence: "This represents a paradigm shift." },
  { word: "pervasive", definition: "普遍的；渗透", difficultyLevel: 5, exampleSentence: "Technology has become pervasive in our lives." },
  { word: "predominant", definition: "主导的；主要", difficultyLevel: 5, exampleSentence: "The predominant opinion is against it." },
  { word: "proliferation", definition: "增殖；扩散", difficultyLevel: 5, exampleSentence: "We are concerned about the proliferation of nuclear weapons." },
  { word: "subsequent", definition: "随后的；后来", difficultyLevel: 5, exampleSentence: "Subsequent events proved us wrong." },
];
