// Demo vocabulary data (same as seed for consistency)
// This is used when in demo mode without a database connection

export interface DemoVocabulary {
  id: string;
  word: string;
  definition: string;
  difficultyLevel: number;
  exampleSentence: string | null;
  createdAt: Date;
  updatedAt: Date;
}

const demoExampleSentenceTranslations: Record<string, string> = {
  achieve: "他努力工作去实现自己的目标。",
  appear: "太阳从云层后面出现了。",
  benefit: "运动有益于你的健康。",
  cause: "吸烟会导致严重的健康问题。",
  chance: "这是你成功的大好机会。",
  change: "气候变化影响着每一个人。",
  choose: "你可以选择任何你喜欢的主题。",
  connect: "这座桥连接着两座岛屿。",
  consider: "请考虑一下我的建议。",
  continue: "比赛将在雨停后继续进行。",
  control: "你需要控制自己的脾气。",
  develop: "我们需要开发新的技术。",
  different: "我们对这个问题有不同的看法。",
  difficult: "期末考试非常困难。",
  effect: "这项新法律带来了积极影响。",
  environment: "我们必须保护我们的环境。",
  experience: "她有多年的教学经验。",
  factor: "时间管理是一个重要因素。",
  focus: "请专注于你的工作。",
  future: "我们需要为未来做规划。",
  adequate: "这项供应不足以满足需求。",
  analyze: "我们需要认真分析这些数据。",
  approach: "我们需要用新的方法处理这个问题。",
  assess: "我们需要先评估一下情况。",
  available: "这些资讯可以在网上找到。",
  avoid: "你应该避免再犯同样的错误。",
  challenge: "要勇敢面对你的挑战。",
  concept: "这个概念很难理解。",
  acquire: "他通过阅读获得了很多知识。",
  alternative: "我们需要找到另一个替代方案。",
};

export function getDemoExampleSentenceTranslation(word: string): string | null {
  return demoExampleSentenceTranslations[word.toLowerCase()] ?? null;
}

export const demoVocabulary: DemoVocabulary[] = [
  {
    id: "demo-1",
    word: "achieve",
    definition: "完成；实现",
    difficultyLevel: 1,
    exampleSentence: "He worked hard to achieve his goal.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-2",
    word: "appear",
    definition: "出现；似乎",
    difficultyLevel: 1,
    exampleSentence: "The sun appeared from behind the clouds.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-3",
    word: "benefit",
    definition: "益处；使受益",
    difficultyLevel: 1,
    exampleSentence: "Exercise benefits your health.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-4",
    word: "cause",
    definition: "原因；导致",
    difficultyLevel: 1,
    exampleSentence: "Smoking can cause serious health problems.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-5",
    word: "chance",
    definition: "机会；可能性",
    difficultyLevel: 1,
    exampleSentence: "This is your big chance to succeed.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-6",
    word: "change",
    definition: "改变；变化",
    difficultyLevel: 1,
    exampleSentence: "Climate change affects everyone.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-7",
    word: "choose",
    definition: "选择；决定",
    difficultyLevel: 1,
    exampleSentence: "You can choose any topic you like.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-8",
    word: "connect",
    definition: "连接；联结",
    difficultyLevel: 1,
    exampleSentence: "The bridge connects the two islands.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-9",
    word: "consider",
    definition: "考虑；认为",
    difficultyLevel: 1,
    exampleSentence: "Please consider my suggestion.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-10",
    word: "continue",
    definition: "继续；持续",
    difficultyLevel: 1,
    exampleSentence: "The game will continue after the rain.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-11",
    word: "control",
    definition: "控制；管理",
    difficultyLevel: 1,
    exampleSentence: "You need to control your temper.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-12",
    word: "develop",
    definition: "发展；开发",
    difficultyLevel: 1,
    exampleSentence: "We need to develop new technologies.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-13",
    word: "different",
    definition: "不同的；差异的",
    difficultyLevel: 1,
    exampleSentence: "We have different opinions on this issue.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-14",
    word: "difficult",
    definition: "困难的；难的",
    difficultyLevel: 1,
    exampleSentence: "The final exam was very difficult.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-15",
    word: "effect",
    definition: "影响；效果",
    difficultyLevel: 1,
    exampleSentence: "The new law had a positive effect.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-16",
    word: "environment",
    definition: "环境；周围",
    difficultyLevel: 1,
    exampleSentence: "We must protect our environment.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-17",
    word: "experience",
    definition: "经验；经历",
    difficultyLevel: 1,
    exampleSentence: "She has years of teaching experience.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-18",
    word: "factor",
    definition: "因素；要素",
    difficultyLevel: 1,
    exampleSentence: "Time management is an important factor.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-19",
    word: "focus",
    definition: "聚焦；焦点",
    difficultyLevel: 1,
    exampleSentence: "Please focus on your work.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-20",
    word: "future",
    definition: "未来；将来",
    difficultyLevel: 1,
    exampleSentence: "We need to plan for the future.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-21",
    word: "adequate",
    definition: "足够的；适当的",
    difficultyLevel: 2,
    exampleSentence: "The supply is not adequate to the demand.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-22",
    word: "analyze",
    definition: "分析；研究",
    difficultyLevel: 2,
    exampleSentence: "We need to analyze the data carefully.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-23",
    word: "approach",
    definition: "方法；途径",
    difficultyLevel: 2,
    exampleSentence: "We need a new approach to this problem.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-24",
    word: "assess",
    definition: "评估；评价",
    difficultyLevel: 2,
    exampleSentence: "We need to assess the situation first.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-25",
    word: "available",
    definition: "可获得的；可利用的",
    difficultyLevel: 2,
    exampleSentence: "This information is available online.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-26",
    word: "avoid",
    definition: "避免；避开",
    difficultyLevel: 2,
    exampleSentence: "You should avoid making the same mistake.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-27",
    word: "challenge",
    definition: "挑战；质疑",
    difficultyLevel: 2,
    exampleSentence: "Face your challenges head-on.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-28",
    word: "concept",
    definition: "概念；观念",
    difficultyLevel: 2,
    exampleSentence: "This concept is difficult to understand.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-29",
    word: "acquire",
    definition: "获得；习得",
    difficultyLevel: 3,
    exampleSentence: "He acquired a lot of knowledge through reading.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-30",
    word: "alternative",
    definition: "可供选择的；替代",
    difficultyLevel: 3,
    exampleSentence: "We need to find an alternative solution.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
